### ISSUE TITLE
Implementing `foldMap` for foldable

### ISSUE THREAD

**Issue by paldepind** [fantasyland/fantasy-land#97] opened 2015-07-08 10:44 UTC
With a foldable it is (or should be) possible to implement `foldMap` in terms of `foldr` (what fantasy land calls `reduce`) and vice versa.

If I have a monoid like this:

```javascript
function _Add(n) {
  this.n = n;
}
_Add.prototype.empty = function() {
  return new _Add(0);
}
_Add.prototype.concat = function(m) {
  return new _Add(this.n + m.n);
}
function Add(n) {
  return new _Add(n);
}
```

`foldMap` should behave like this when given a traversable of numbers and the above constructor function.

```javascript
assert.deepEqual(foldMap(Add, traversableFromArray([1, 2, 3, 4])), Add(10));
```

But the straightforward implementation doesn't work:

```javascript
function foldMap(f, t) {
  t.reduce(f, empty);
  //          ╰── does not work, there is no empty
}
```

The problem is that `foldMap` doesn't know how to create an identity element of the monoid inside the passed foldable. The easiest solution would be to do the same as what fantasy land does in a few places and demand an additional argument to help the implementation. In this case if users where required to pass an empty value then the simple implementation would work.

But such an argument results in an inferior API with unfortunate ugliness.

Since the function passed to `foldMap` is required to return a monoid it is possible, with a bit of clunkiness, to work around the need for an initial empty value. An implementation that satisfies the previous assertion is given below:

```javascript
    var empty = {};
    function foldMap(f, t) {
      return t.reduce(function(acc, n) {
        return acc === empty ? f(n) : concat(acc, f(n));
      }, empty);
    }
```

We create a dummy empty value that contains a pointer to an object (which we now will be unique) and uses it inside the function passed to `reduce` to ignore the initial accumulator value.

This seems to result in the desired `foldMap` at the cost of elegance in the implementation.

Any thoughts?

**Comment by joneshf** [comment] 2015-07-08 11:06
The problem with using some arbitrary value for the empty is that now your function doesn't do the right thing for an empty `Foldable`. Like if you have an empty array or whatever, instead of getting back the right thing, you now get back a plain object.

There are at least two ways to handle this:

1. Only operate on "non-empty" `Foldable`s--`Foldable1` as they're usually called in haskell and friends.
In this case, you can relax the constraint to `Semigroup`, and since you are guaranteed to have at least one element, you can always have an "initial" value.
1. Take the `Monoid` as an argument, as you suggested. Although the api is slightly more cumbersome, it's "The Right Way". Let's not forget that a signature like:

    ```haskell
    foldMap :: (Foldable f, Monoid m) => (a -> m) -> f a -> m
    ```

    compiles to something like:

    ```haskell
    foldMap' :: foldableDict f -> monoidDict m -> (a -> m) -> f a -> m
    ```

    depending on the compiler. So there's no reason to expect js to have some way to circumvent the need to pass around the second dictionary.

**Comment by CrossEye** [comment] 2015-07-08 14:59
> Take the Monoid as an argument, as you suggested. Although the api is slightly more cumbersome, it's "The Right Way". Let's not forget that a signature like:
> ```haskell
> foldMap :: (Foldable f, Monoid m) => (a -> m) -> f a -> m
> ```
> compiles to something like:
> ```haskell
> foldMap' :: foldableDict f -> monoidDict m -> (a -> m) -> f a -> m
> ```
> depending on the compiler. So there's no reason to expect js to have some way to circumvent the need to pass around the second dictionary.

The problem is that the specification is fuzzy here:

> A value which has a Monoid must provide an `empty` method on itself **or** its `constructor` 
object. 

(emphasis added)

If someone decides to implement `empty` only on the instances and not on the constructor/dictionary, then passing this to @paldepind's `foldMap` won't work.  This was discussed (perhaps to death) in #88.

**Comment by bergus** [comment] 2015-07-08 16:43
Yeah, this sounds like a duplicate of #88. There is no convincing solution to overcome JavaScript's lack of type inference.

**Comment by CrossEye** [comment] 2015-07-08 17:20
@bergus:
The answer from @joneshf would work fine if the specification simply required that a Monoid must provide an `empty` method on its `constructor` object.  It's the ambiguity in the definition that seems to cause a problem.

**Comment by bergus** [comment] 2015-07-08 22:44
@CrossEye You mean the solution with the "type dictionary"? I guess passing in `_Add.prototype` (for the above example) would work quite well, only the problem that you *have to* pass that in remains.

**Comment by davidchambers** [comment] 2015-07-08 23:11
@bergus, you're right that one can provide `_Add` or `_Add.prototype` as appropriate. Authors of libraries which accept values of any FL-compliant type, though, must write things like

```javascript
typeof x.empty === 'function' ? x : x.constructor
```

to decide which "dictionary" to provide. I believe this is why @CrossEye suggests the spec should specify one location for `empty` rather than two.

**Comment by bergus** [comment] 2015-07-08 23:53
Ahh I think I'm getting what you're arguing at. I always was under the impression that if we use type dictionaries as arguments, then they are infectious and will pervade the entire codebase anyway. Only if a type is instantiated, the specific dictionary object is required, and can be chosen appropriately (depending on the implementation of that particular data type).
But you're proposing to extract the type dictionary from a given value of an arbitrary instance in library code?! For that, allowing `.empty`/`.of` to be found only on the constructor is indeed unfortunate. If we did require them to be instance properties (or inherited from the prototype), then every value itself could be used as the dictionary (if that doesn't leak memory or secure information).

Alternatively, I could envision a new method/property to extract this dictionary from arbitrary instances. Expanding on the above example, it might be
```js
var typedict = getSymbol("fantasyland.typeDictionary")
Add.type = _Add.prototype[typedict] = _Add.prototype;
```
so that a user could pass in `Add.type` as a type argument where required, and libraries could extract `instance[typedict]` from every arbitrary instance to get an object with all the functions/methods for that type.

**Comment by CrossEye** [comment] 2015-07-09 00:10
@bergus: I've been thinking of building an implementation of something very similar to that idea, using the public API of FantasyLand as a purely functional rather than OO-style implementation.  I won't be able to get to it for several weeks, but I'm looking forward to seeing if I can get it to work in a clean manner.  It would _still_ mean passing in either `empty` or the type into `foldMap`, but for something like `map` or `concat` I could extract the appropriate versions from the instances, just as you say.  I've been thinking about this for some time, and once I clear one other thing of my plate, it's next up.

**Comment by puffnfresh** [comment] 2015-07-09 01:30
I'd like to see a rewrite of the spec using explicit dictionaries for everything. My theory is that'd be more useful than the current spec but much less convenient. Definitely happy to do that as Fantasy Land 2 if it actually works, though.

**Comment by paldepind** [comment] 2015-07-09 07:06
@joneshf 

> The problem with using some arbitrary value for the empty is that now your function doesn't do the right thing for an empty Foldable. Like if you have an empty array or whatever, instead of getting back the right thing, you now get back a plain object.

Indeed. you're right. That is the catch.

@bergus 

> Yeah, this sounds like a duplicate of #88.

How? The topic here is "how to implement `foldMap`". It is only vaguely related to #88.

`foldMap` could simply require users to pass in the identity element of the monoid in the foldable and then the implementation wouldn't have to worry about finding the `empty` method (of course then the user would have to know where to find it instead).

@CrossEye 

> I've been thinking of building an implementation of something very similar to that idea, using the public API of FantasyLand as a purely functional rather than OO-style implementation. I won't be able to get to it for several weeks, but I'm looking forward to seeing if I can get it to work in a clean manner. It would still mean passing in either empty or the type into foldMap, but for something like map or concat I could extract the appropriate versions from the instances, just as you say.

I don't get this: "for something like map or concat I could extract the appropriate versions from the instances". But that is as easy as accessing the `map` property right?

@puffnfresh 

Can you expand on the more useful part? Usefulness and convenience often go hand in hand in my experience.

**Comment by puffnfresh** [comment] 2015-07-09 07:13
Useful: we can implement foldMap.

Inconvenient:

```js
someFantasyFoldableLibrary.foldMap(foldableList, monoidNumber, function(a) { return a.length; }, ["hello", "world"]);
```

**Comment by paldepind** [comment] 2015-07-09 07:21
> Useful: we can implement foldMap.

We can do that today as well:

```javascript
function foldMap(monoid, f, foldable) {
  return foldable.reduce(function(acc, n) {
    return acc.concat(f(n));
  }, monoid.empty());
}
```

**Comment by CrossEye** [comment] 2015-07-09 12:22
We can do that today as well:

```js
function foldMap(monoid, f, foldable) {
  return foldable.reduce(function(acc, n) {
    return acc.concat(f(n));
  }, monoid.empty());
}
```

You can't necessarily do that by the spec, which allows the user to define `empty` only on instances and not the constructor.  So, while it may work for a subset of FantasyLand-compatible Monoids, it will not work universally.

**Comment by CrossEye** [comment] 2015-07-09 12:44
@paldepind:
> I don't get this: "for something like map or concat I could extract the appropriate versions from the instances". But that is as easy as accessing the map property right?

I'm imagining a type registry, perhaps based on a Symbol, as @bergus said, but in any case accessible to `Lib.concat` so that when a user calls `Lib.concat(obj1, obj2)` it would scan the Semigroup registry for some type `T` such that `R.is(T, obj1) && R.is(T, obj2)`. <sup>1</sup>  (It would have to be somewhat more sophisticated, as it should find the _most specific_ type, but that's just a detail at the moment).  And then from the type definition, it would take the appropriate version of `concat` and apply it to `obj1` and `obj2`.  This could be a method on the object, but would not have to be, and my preference would be not to implement it that way.


-----
<sup>1</sup> `R.is` is a Ramda function that just checks if `param2` is an instance of the constructor `param1`: http://ramdajs.com/docs/#is

**Comment by joneshf** [comment] 2015-07-09 13:10
So a compiler?

**Comment by joneshf** [comment] 2015-07-09 13:16
> You can't necessarily do that by the spec, which allows the user to define `empty` only on instances and not the constructor. So, while it may work for a subset of FantasyLand-compatible Monoids, it will not work universally.

I think this makes the solution to #88 pretty clear then. If we force these "static" methods to be defined on the constructor, we gain more power.

**Comment by paldepind** [comment] 2015-07-09 14:00
@CrossEye 

> You can't necessarily do that by the spec, which allows the user to define empty only on instances and not the constructor. So, while it may work for a subset of FantasyLand-compatible Monoids, it will not work universally.

This `flatMap` require an object with an `empty` method so users can either pass the prototype, the constructor or an instance. It doesn't matter to the point I'm trying to make: `flatMap` can be implemented with the current spec. I really don't want this discussion to be about the constructor issue – it is a separate thing.

> I'm imagining a type registry, perhaps based on a Symbol, as @bergus said, but in any case accessible to Lib.concat so that when a user calls Lib.concat(obj1, obj2) it would scan the Semigroup registry for some type T such that R.is(T, obj1) && R.is(T, obj2). 1 (It would have to be somewhat more sophisticated, as it should find the most specific type, but that's just a detail at the moment). And then from the type definition, it would take the appropriate version of concat and apply it to obj1 and obj2. This could be a method on the object, but would not have to be, and my preference would be not to implement it that way.

I still don't get it. What is the advantage of this compared to just using a `concat` method? You would have to have access to the type information and if you have that you could just as well have the methods themselves. The problem in this case is that for an empty foldable there is no information about the monoid inside it unless explicitly passed. And if you explicitly pass it then just passing the methods would be easier.

**Comment by CrossEye** [comment] 2015-07-09 14:58
> I think you've made the solution to #88 pretty clear then. If we force these "static" methods to be defined on the constructor, we gain more power.

That's the conclusion I'd come to, and it's what I'm planning on playing around with, albeit with a somewhat different API.  I expect to keep much of the essence of FantasyLand in my attempt, but we'll see.  At the very least, I expect that things like `concat`, `empty`, `of`, `map`, etc. will retain their meanings, and I would keep the same names. (I wouldn't choose `bind` or `flatMap` instead of `chain`, etc.)

**Comment by CrossEye** [comment] 2015-07-09 17:29
@paldepind:
> This `flatMap` require an object with an `empty` method so users can either pass the prototype, the constructor or an instance. It doesn't matter to the point I'm trying to make: `flatMap` can be implemented with the current spec.

`foldMap`, surely?

If all the user is supposed to pass in is something that has an `emtpy()` method, and if it's only going to be used once, might it not be better just for them to pass an/the empty instance directly?  I know you mentioned this above, but that seems cleaner than the suggestion that you can pass any instance or the constructor, so long as whatever you pass has `empty()` defined on it.

In the end, though, I think to your fundamental question, the answer is yes, you have to supply something more than the function and the Foldable in order to handle the empty case.  This shouldn't be such a surprise:  `foldl`/`foldr` do have their `foldl1`/`foldr1` counterparts that don't need that third parameter, but then throw errors if their Foldables are empty.

> I still don't get it. What is the advantage of this compared to just using a `concat` method?

Perhaps there's none.  It seems like a really good idea to me, but I haven't proven it, even to myself yet..  The thought is that I'd rather be programming like this:

```js
    var myMonoidImpl3 = concat(myMonoidImpl1, myMonoidImpl2);
    var maybeSquare = pipe(getNextValue, Maybe.of, map(square))(currentVal);
    var foldMap = curry(function(monoid, fn, foldable) {
      return reduce(function(acc, n) {
        concat(acc, f(n));
      }, empty, foldable);
    });
    var result = foldMap(fn, MyMonoid.empty, myTreeOfMyMonoids)
```

than like this:

```js
    var myMonoidImpl3 = myMonoidImpl1.concat(myMonoidImpl2);
    var maybeSquare = pipe(getNextValue, Maybe.of, val => val.map(square))(currentVal);
    function foldMap(monoid, f, foldable) {
      return foldable.reduce(function(acc, n) {
        return acc.concat(f(n));
      }, monoid.empty());
    }
    var result = foldMap(MyMonoid, fn, myTreeOfMyMonoids)
```

Such an implementation would help me work in this preferred manner.  We'll see if I can make it work, make it usable, and make it efficient.  But that API is the goal.

**Comment by paldepind** [comment] 2015-07-09 17:36
@CrossEye 

> If all the user is supposed to pass in is something that has an emtpy() method, and if it's only going to be used once, might it not be better just for them to pass an/the empty instance directly? I know you mentioned this above, but that seems cleaner than the suggestion that you can pass any instance or the constructor, so long as whatever you pass has empty() defined on it.

I agree. I think the main counterargument is consistency with other function where you have to pass a dictionary.

> Such an implementation would help me work in this preferred manner. We'll see if I can make it work, make it usable, and make it efficient. But that API is the goal.

But you can mostly achieve that just by having functions that invoke the respective methods (like `R.invoker`)?

**Comment by CrossEye** [comment] 2015-07-09 20:08
> I agree. I think the main counterargument is consistency with other function where you have to pass a dictionary.

AFAIK, the only places where that would be necessary is when you need to make reference to `of` or `empty`.  All the other FL functions require at least one instance of the type, which can then serve as your dictionary for the remaining relevant functions.  These two are the special cases, and that's why I brought up #88.

>> Such an implementation would help me work in this preferred manner. We'll see if I can make it work, make it usable, and make it efficient. But that API is the goal.

> But you can mostly achieve that just by having functions that invoke the respective methods (like `R.invoker`)?

I could.  I don't think I'm getting my ideas or my rationale across at all, but its probably because it's still fairly ill-formed for me.  When I get closer to trying it (probably two weeks or so) I'll likely be back asking questions and advice, and I won't be surprised if that advice is simply "Don't do it!"  :smile:

**Closed** 2015-08-10 08:23 UTC
