### ISSUE TITLE
Functors and functions both called `f` can be confusing

### ISSUE THREAD

**Issue by dmitriz** [fantasyland/fantasy-land#289] opened 2018-05-04 03:02 UTC
In https://github.com/fantasyland/fantasy-land#map-method
the letter `f` denotes a functor:
```js
map :: Functor f => f a ~> (a -> b) -> f b
```
But in the next line the same `f` is a function:
```js
u.map(x => f(g(x)))
```
Would it be less confusing to use different letters perhaps?

**Comment by dmitriz** [comment] 2018-05-04 09:39
@davidchambers 
> Suggestions? `g(h(x))`?

It is less confusing, but `g` and `h` still look too similar to `f`.
Here the meaning of `f` is different from anything else.
It would be nice to make it look fundamentally different, e.g. as the capital `F` instead of `f`,
as in the math books.

**Comment by davidchambers** [comment] 2018-05-04 09:56
Capitalized identifiers refer to concrete types, such as `Boolean` in `filter :: Filterable f => f a ~> (a -> Boolean) -> f a`.

**Comment by i-am-tom** [comment] 2018-05-04 12:28
It bears repeating that these identifiers don't have to be single letters; would it be easier if the definition were simply `map :: Functor flType => flType a -> (a -> b) -> flType b`?

**Comment by dmitriz** [comment] 2018-05-04 12:30
> Capitalized identifiers refer to concrete types, such as `Boolean in filter :: Filterable f => f a ~> (a -> Boolean) -> f a`.

Since `Boolean` is written fully and `F` an abbreviation, that would still look different.

**Comment by i-am-tom** [comment] 2018-05-04 12:31
@dmitriz The point is that, in Haskell, a capital letter _always_ indicates a concrete type, class, family, etc - never a variable. It would be a shame to diverge, imo

**Comment by dmitriz** [comment] 2018-05-04 12:37
@i-am-tom
> The point is that, in Haskell, a capital letter always indicates a concrete type, class, family, etc - never a variable. It would be a shame to diverge, imo

Haskell suffers from the same confusion - functors and functions are called `f`. I have never understood why. As if they run out of letters :)

**Comment by davidchambers** [comment] 2018-05-04 12:43
In Haskell, types and values live in different namespaces. This allows punning such as `Identity :: a -> Identity a`, which is very nice in my opinion.

**Comment by joneshf** [comment] 2018-05-04 12:55
They live in different namespaces in FL as well.

**Comment by gabejohnson** [comment] 2018-05-04 12:56
This looks like a duplicate of #217 to me.

**Comment by dmitriz** [comment] 2018-05-04 14:02
@davidchambers 
> In Haskell, types and values live in different namespaces. This allows punning such as Identity :: a -> Identity a, which is very nice in my opinion.

Do you mean using the same word to mean different things, depending on the context? Does that not expose the code to more bugs due to possible messed up context e.g. by mistake?
I always find it harder to read, as it requires additional mental effort to recoginize the context.

**Comment by dmitriz** [comment] 2018-05-04 14:07
@gabejohnson 
> This looks like a duplicate of #217 to me.

True, was long time ago, so I forgot it ;)

Which, however, lead to PR with many more suggestions,
that was closed by @davidchambers [for reasons not related to this issue](https://github.com/fantasyland/fantasy-land/pull/218#issuecomment-284707077)

**Comment by joneshf** [comment] 2018-05-04 14:09
Per @gabejohnson's comment, closing in favor of #217. If there's more to discuss, let's reopen #217 and continue the discussion there. If that's wrong, and this issue is different from #217, let's re-open and continue discussion here.

**Closed by joneshf** 2018-05-04 14:09 UTC

**Comment by dmitriz** [comment] 2018-05-04 14:13
@joneshf 
I will leave it at that, I feel it does create some extra confusion for the newcomers,
but if no one feels the need to change it, I'm not going to press it ;)
