### ISSUE TITLE
Filterable algebra?

### ISSUE THREAD

**Issue by Raynos** [fantasyland/fantasy-land#33] opened 2013-04-18 19:27 UTC
`.map` and `.chain` are cool for writing higher order functions over things.

Another primitive I use a lot is `.filter` and I don't know how to implement in terms of `.map` / `.ap` / `.chain`.

Is there an algebra for it?

**Comment by joneshf** [comment] 2016-05-30 18:45
We could take a cue from `witherable` and provide `mapMaybe` as the method without pulling in all of `witherable`. `filter` is easily derived from it. Though it would add a specific dependency on an implementation of `Maybe a` existing somewhere.

There should be at least one law (maybe more?):

```js
u.mapMaybe(Just) == u
```

And you should be able to derive `Functor`s `map` from it:

```js
function (f) { return this.mapMaybe(x => Just(f(x))); }
```

And of course `filter` is:

```js
function (p) { return this.mapMaybe(x => p(x) ? Just(x) : Nothing); }
```

**Comment by joneshf** [comment] 2016-05-30 18:47
Also, `catMaybes` comes for free:

```js
function () { this.mapMaybe(x => x); }
```

**Comment by joneshf** [comment] 2016-06-01 04:37
Oh look, prior art:

* https://github.com/fumieval/witherable/issues/10 
* https://github.com/reflex-frp/reflex/issues/19
* https://github.com/reflex-frp/reflex/pull/44

**Comment by puffnfresh** [comment] 2016-06-01 05:19
A useful function:

```haskell
unite :: (MonadPlus m, Foldable t) => (a -> t (m b)) -> m a -> m b
unite f = (>>= (getAlter . foldMap Alter . f))
```

A generalised version of `mapMaybe` might use the above and look something like:

```haskell
(MonadPlus m, Traversable t) => (a -> t b) -> m a -> m b
```

**Comment by joneshf** [comment] 2016-06-06 02:20
`unite` = generalized `catMaybes`?

Seems like the `MonadPlus` constraint limits what can implement it though. We'd lose `Map a b`, `ZipList a`, and `Validation a b` to name a few.

I like the idea of a `Foldable` constraint though.

**Comment by puffnfresh** [comment] 2016-06-06 02:37
You can change the constraint a bit to get:

```haskell
collapse :: (Alternative m, Foldable t) => t a -> m a
collapse = foldr ((<|>) . pure) empty
```

Given that Foldable composes, you can then recover `catMaybes`:

```haskell
let catMaybes :: [Maybe a] -> [a]
    catMaybes = collapse . Compose
in catMaybes [Just 1, Nothing, Just 2] == [1, 2]
```

**Comment by safareli** [comment] 2016-10-19 14:36
you can also do
```hs
filter :: (Applicative f, Foldable f, Monoid (f a)) => (a -> Bool) -> f a -> f a
filter p = foldMap (\a -> if p a then pure a else mempty)
```

**Comment by davidchambers** [comment] 2017-03-05 17:21
Sanctuary currently provides [`S.filter`][1] and [`S.filterM`][2] (which wrap [`Z.filter`][3] and [`Z.filterM`][4] respectively).

As a result of sanctuary-js/sanctuary#359 it's now apparent that neither `filter(odd, Just(4))` nor `filterM(odd, Just(4))` is valid due to the `Monoid (m a)` constraints. To filter values of type `Maybe a` we need [`mfilter`][5], which requires MonadPlus.

Is adding MonadPlus to the specification a good idea, do you think?


[1]: https://sanctuary.js.org/#filter
[2]: https://sanctuary.js.org/#filterM
[3]: https://github.com/sanctuary-js/sanctuary-type-classes#filter
[4]: https://github.com/sanctuary-js/sanctuary-type-classes#filterM
[5]: http://hackage.haskell.org/package/base-4.9.1.0/docs/Control-Monad.html#v:mfilter

**Comment by joneshf** [comment] 2017-03-06 03:23
Why are neither of those examples valid?

**Comment by safareli** [comment] 2017-03-06 10:15
you can do it with `(Alternative m, Monad m) => m` constraint:
```js
// :: (Alternative m, Monad m) => (a -> Boolean, m a) -> m a
const mfilter = (p,ma) => {
 const T = ma.constructor
 return ma.chain(a => p(a) ? T.of(a) : T.zero()
}
```

**Comment by davidchambers** [comment] 2017-03-06 15:14
> Why are neither of those examples valid?

From the [Monoid][1] spec:

> A value that implements the Monoid specification must also implement the [Semigroup][2] specification.

`Just(4)` cannot satisfy Semigroup, so by extension cannot satisfy Monoid.

As @safareli pointed out, though, `Just(4)` can satisfy Alternative! The solution, therefore, is to replace the `Monoid (m a)` constraint with an `Alternative m` constraint. I've opened sanctuary-js/sanctuary-type-classes#37 to do exactly this.


[1]: https://github.com/fantasyland/fantasy-land#monoid
[2]: https://github.com/fantasyland/fantasy-land#semigroup

**Comment by joneshf** [comment] 2017-03-06 17:53
Why can't `Maybe a` be a `Semigroup`?

**Comment by safareli** [comment] 2017-03-06 18:52
> Why can't `Maybe a` be a `Semigroup`?
`Maybe a` can be  a `Semigroup` only when `a` is also `Semigroup`.

**Comment by joneshf** [comment] 2017-03-06 19:42
1. Why is that a problem?
2. Can't you also do:

    ```js
    const Nothing = {
      concat: x => x,
    };
    const Just = x => ({
      concat: _ => x,
    });
    ```
    or
    ```js
    const Nothing = {
      concat: x => x,
      isJust: false,
    };
    const Just = x => ({
      concat: y => y.isJust ? y : x,
      isJust: true,
    });
    ```

**Comment by safareli** [comment] 2017-03-06 19:59
Technically you can you can make any `Alternative` a `Monoid`:

```js
T.empty = T.zero
T.prototype.concat = T.prototype.alt
```

The definition of `concat` you provided is more `alt` then `concat`.

Ideally we should be able to make `Maybe a`, `Monoid` when `a` is `Monoid`
```js
const MaybeOf = M => {
  const TypeRep = {
    empty: M.empty,
  }

  const Just = value => {
    value,
    tag: 'Just',
    concat: b => Just(b.tag == 'Just' ? value.concat(b.value) : value)
    constructor: TypeRep,
  }

  const Nothing = {
    value,
    tag: 'Nothing',
    concat: b => b,
    constructor: TypeRep,
  }

  TypeRep.of = Just
  TypeRep.Just = Just
  TypeRep.Nothing = Nothing

  return TypeRep
}

```

But it becomes problematic when you start defining `map`

**Comment by xaviervia** [comment] 2017-03-06 22:32
@safareli could this be two different `Maybe` variations? I see the point of @joneshf of making `Maybe` a Semigroup. 

The `Maybe a` that is a Monoid when `a` is a Monoid sounds like one of many possible interpretations of `Maybe.concat`. It would mean that `Maybe` is not a Monoid per se, and you cannot really make assumptions about it being a Monoid if you get a Maybe and don’t know which type it is parametrized with, which sounds odd to me. I haven’t seen many cases in which the parameter type changes the type class of the parametrized type.

**Comment by davidchambers** [comment] 2017-03-06 22:39
> Why is that a problem?

Because we'd like `S.filterM(S.odd, S.Just(0))` to evaluate to `Nothing`, but it's a type error:

```javascript
S.filterM(S.odd, S.Just(0));
// ! TypeError: Type-class constraint violation
//
//   filterM :: (Monad m, Monoid m) => (a -> Boolean) -> m a -> m a
//                        ^^^^^^^^                       ^^^
//                                                        1
//
//   1)  Just(0) :: Maybe Number, Maybe FiniteNumber, Maybe Integer, Maybe ValidNumber
//
//   ‘filterM’ requires ‘m’ to satisfy the Monoid type-class constraint; the value at position 1 does not.
```

As for your second point, @joneshf, you're quite right to point out that this claim is false:

> `Just(4)` cannot satisfy Semigroup, so by extension cannot satisfy Monoid.

It should read *does not* rather than *cannot*.

The question is then whether we should adopt your version of `Maybe#fantasy-land/concat`. Letting our desire to filter values of type `Maybe a` dictate the `concat` semantics seems like the tail wagging the dog. Why go to such lengths to satisfy Monoid when we could satisfy Alternative instead?

The `concat` and `alt` semantics of Sanctuary's Maybe type match those of Haskell's Maybe type:

```haskell
> Just "abc" <> Just "def"
Just "abcdef"

> Just "abc" <|> Just "def"
Just "abc"

> mfilter odd (Just 0)
Nothing
```

> I haven’t seen many cases in which the parameter type changes the type class of the parametrized type.

Try evaluating this in `ghci`, @xaviervia:

```haskell
> Just 123 <> Just 456
```

Again, @safareli and I are referencing the Haskell behaviour. The Haskell definition of `(<>)` for `Maybe a` is not the only valid definition, but it is certainly useful in some contexts.

**Comment by joneshf** [comment] 2017-03-07 01:55
> Because we'd like S.filterM(S.odd, S.Just(0)) to evaluate to Nothing, but it's a type error:

That works on the docs here: https://sanctuary.js.org/#filterM I'm still confused what the problem is. If you can only make `Maybe a` a `Monoid` only if `a` is also a `Monoid`, then you should rightly get an error when you pass a `Maybe a` where `a` is not a `Monoid`.

> Letting our desire to filter values of type Maybe a dictate the concat semantics seems like the tail wagging the dog. Why go to such lengths to satisfy Monoid when we could satisfy Alternative instead?

Chasing `Monoid`s and `Alternative`s in order to get an approximation of `filter` is equally tail-wagging. Why not just define `filter` and be done with it? We can add the algebra to the spec with laws so there isn't a need to debate whether something should be a `Monoid`, an `Alternative`, or whatever else. `filter` is a worthwhile enough function with enough behavior that it should get its own algebra instead of being derived from other algebras. Not to mention that if we push on `filter` a bit we get things like `partition`, `filterMap`, `wither`, etc.

**Comment by davidchambers** [comment] 2017-03-07 12:18
> > Because we'd like `S.filterM(S.odd, S.Just(0))` to evaluate to `Nothing`, but it's a type error:
>
> That works on the docs here: <https://sanctuary.js.org/#filterM> I'm still confused what the problem is.

It currently works because Sanctuary's Maybe type defines `fantasy-land/concat` unconditionally. This is not correct, though, and leads to invalid code "working" in some cases and throwing errors with unhelpful descriptions in other cases:

```javascript
S.concat(S.Just(0), S.Nothing);
// => Just(0)

S.concat(S.Just(0), S.Just(0));
// ! Semigroup.methods.concat(...) is not a function
```

The fix for this is to define `fantasy-land/concat` for a Just only if the Just's value satisfies <code><a href="https://github.com/sanctuary-js/sanctuary-type-classes#Semigroup">Z.Semigroup</a>.test</code> (sanctuary-js/sanctuary#359). There are several consequences of this change:

  - `S.Just(0)` no longer satisfies Semigroup;
  - as a result it no longer satisfies Monoid; and
  - as a result it can no longer be used with [`S.filter`][1] and [`S.filterM`][2].

In order to continue to support filtering values of type `Maybe a` without changing the Maybe type's `concat` semantics (which match those of Haskell's Maybe type), we could:

  - provide a separate function such as `filterMaybe :: (a -> Boolean) -> Maybe a -> Maybe a`;
  - dispatch to a `sanctuary/filter` method or some other non-FL method; or
  - replace the `Monoid (m a)` constraint of [`S.filterM`][2] with an `Alternative m` constraint.

I favour the last option.

> Why not just define `filter` and be done with it? We can add the algebra to the spec with laws so there isn't a need to debate whether something should be a `Monoid`, an `Alternative`, or whatever else.

Sounds great to me! If and when Fantasy Land specifies Filterable we will replace [`S.filter`][1] and [`S.filterM`][2] with a single `S.filter :: Filterable f => (a -> Boolean) -> f a -> f a`. Until that point, though, we can make do with type classes already specified. :)


[1]: https://sanctuary.js.org/#filter
[2]: https://sanctuary.js.org/#filterM

**Closed** 2018-01-06 20:25 UTC
